//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supershop.AdminPanelForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customerdetails
    {
        public long Id { get; set; }
        public string CustomerName { get; set; }
        public string Contact { get; set; }
        public string EmailAddress { get; set; }
        public string StoreName { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<long> Price { get; set; }
        public string LicenseCode { get; set; }
    }
}
