//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supershop.AdminPanelForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userlicense
    {
        public long Id { get; set; }
        public string LicenseKey1 { get; set; }
        public string LicenseKey2 { get; set; }
        public string LicenseKey3 { get; set; }
        public string LicenseKey4 { get; set; }
        public string LicenseKey5 { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<long> User_Id { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
